# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameOver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameOver(object):
    def setupUi(self, GameOver):
        GameOver.setObjectName("GameOver")
        GameOver.resize(180, 160)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameOver)
        self.verticalLayout.setObjectName("verticalLayout")
        self.finalLabel = QtWidgets.QLabel(GameOver)
        self.finalLabel.setObjectName("finalLabel")
        self.verticalLayout.addWidget(self.finalLabel)
        self.okButton = QtWidgets.QPushButton(GameOver)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)

        self.retranslateUi(GameOver)
        self.okButton.clicked.connect(GameOver.accept)
        QtCore.QMetaObject.connectSlotsByName(GameOver)

    def retranslateUi(self, GameOver):
        _translate = QtCore.QCoreApplication.translate
        GameOver.setWindowTitle(_translate("GameOver", "Game Over"))
        self.finalLabel.setText(_translate("GameOver", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Game Over<br/><br/>Final score<br/>0</span></p></body></html>"))
        self.okButton.setText(_translate("GameOver", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameOver = QtWidgets.QDialog()
    ui = Ui_GameOver()
    ui.setupUi(GameOver)
    GameOver.show()
    sys.exit(app.exec_())
