# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_GameView(object):
    def setupUi(self, GameView):
        GameView.setObjectName("GameView")
        GameView.resize(800, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scoreLabel = QtWidgets.QLabel(GameView)
        self.scoreLabel.setObjectName("scoreLabel")
        self.horizontalLayout.addWidget(self.scoreLabel)
        self.sPointsLabel = QtWidgets.QLabel(GameView)
        self.sPointsLabel.setObjectName("sPointsLabel")
        self.horizontalLayout.addWidget(self.sPointsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.playField = QtWidgets.QGraphicsView(GameView)
        self.playField.setObjectName("playField")
        self.playField.resizeEvent = lambda x: self.playField.fitInView(self.playField.sceneRect(), QtCore.Qt.KeepAspectRatio)
        self.verticalLayout.addWidget(self.playField)

        self.retranslateUi(GameView)
        QtCore.QMetaObject.connectSlotsByName(GameView)

    def retranslateUi(self, GameView):
        _translate = QtCore.QCoreApplication.translate
        GameView.setWindowTitle(_translate("GameView", "bhQt"))
        self.scoreLabel.setText(_translate("GameView", "<html><head/><body><p><span style=\" font-size:16pt;\">Score</span></p></body></html>"))
        self.sPointsLabel.setText(_translate("GameView", "<html><head/><body><p align=\"right\"><span style=\" font-size:16pt;\">0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameView = QtWidgets.QWidget()
    ui = Ui_GameView()
    ui.setupUi(GameView)
    GameView.show()
    sys.exit(app.exec_())
